default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: platogo

development:
  <<: *default
  database: stimulus_example_development

test:
  <<: *default
  database: stimulus_example_test

production:
  <<: *default
  database: stimulus_example_production
  username: stimulus_example
  password: <%= ENV['STIMULUS_EXAMPLE_DATABASE_PASSWORD'] %>
